2018-01-20 15:51:29.656 [error] <0.709.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.714.0> exit with reason normal in context child_terminated
2018-01-20 15:51:29.693 [info] <0.33.0> Application lager started on node nonode@nohost
2018-01-20 15:51:29.734 [info] <0.770.0> Setup running ...
2018-01-20 15:51:29.739 [info] <0.770.0> Directories verified. Res = ok
2018-01-20 15:51:29.739 [info] <0.770.0> Setup finished processing hooks (Mode=normal)...
2018-01-20 15:51:29.739 [info] <0.33.0> Application setup started on node nonode@nohost
2018-01-20 15:51:29.770 [info] <0.777.0>@exometer_report:do_start_reporters:632 Starting reporters with []
2018-01-20 15:51:29.771 [info] <0.33.0> Application exometer_core started on node nonode@nohost
2018-01-20 15:51:29.772 [info] <0.33.0> Application pobox started on node nonode@nohost
2018-01-20 15:51:29.778 [info] <0.33.0> Application elixometer started on node nonode@nohost
2018-01-20 15:51:29.779 [error] <0.793.0> CRASH REPORT Process <0.793.0> with 0 neighbours exited with reason: {start_spec,{duplicate_child_name,'Elixir.Jorb.Fetcher'}} in gen_server:init_it/6 line 349
2018-01-20 15:51:29.780 [error] <0.791.0> CRASH REPORT Process <0.791.0> with 0 neighbours exited with reason: {{start_spec,{duplicate_child_name,'Elixir.Jorb.Fetcher'}},{'Elixir.Jorb.Application',start,[normal,[]]}} in application_master:init/4 line 134
2018-01-20 15:51:29.780 [info] <0.33.0> Application jorb exited with reason: {{start_spec,{duplicate_child_name,'Elixir.Jorb.Fetcher'}},{'Elixir.Jorb.Application',start,[normal,[]]}}
