2018-01-20 15:51:29.656 [error] <0.709.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.714.0> exit with reason normal in context child_terminated
2018-01-20 15:51:29.779 [error] <0.793.0> CRASH REPORT Process <0.793.0> with 0 neighbours exited with reason: {start_spec,{duplicate_child_name,'Elixir.Jorb.Fetcher'}} in gen_server:init_it/6 line 349
2018-01-20 15:51:29.780 [error] <0.791.0> CRASH REPORT Process <0.791.0> with 0 neighbours exited with reason: {{start_spec,{duplicate_child_name,'Elixir.Jorb.Fetcher'}},{'Elixir.Jorb.Application',start,[normal,[]]}} in application_master:init/4 line 134
